services:
  - type: web
    name: floodguard-backend
    env: python
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: EARTH2_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: MAPS_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        sync: false

  - type: web
    name: floodguard-frontend
    env: node
    rootDir: frontend
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npx serve -s build -l $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        sync: false

