services:
  - type: web
    name: floodguard-app
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: EARTH2_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: MAPS_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: REACT_APP_API_URL
        value: ""

